### PR TITLE
Add spotlights metadata

### PR DESCRIPTION
**Pull request by wakibi**
This adds spotlights to the Analyst UI

### CODE REVIEW

**Comment by akmiller01** [comment]
Looks good in theory! Have you had a chance to test it on staging?

**Comment by wakibi** [comment]
No, have only tested on my local machine. I think there is no way to specify a branch for this repo when testing using `docker-compose exec web python manage.py update_csv_files` as per [this](https://github.com/devinit/ddw-analyst-ui/issues/424) issue. Perhaps @edwinmp can clarify?

**Comment by akmiller01** [comment]
> I think there is no way to specify a branch for this repo when testing

Good point. Maybe we need to amend that management command to allow for different branches on staging for testing?

**Comment by edwinmp** [comment]
> > I think there is no way to specify a branch for this repo when testing
> 
> Good point. Maybe we need to amend that management command to allow for different branches on staging for testing?

@wakibi want to add that as part of this update?

**Comment by wakibi** [comment]
> > > I think there is no way to specify a branch for this repo when testing
> > 
> > 
> > Good point. Maybe we need to amend that management command to allow for different branches on staging for testing?
> 
> @wakibi want to add that as part of this update?

Sure. Let me work on this

**Comment by wakibi** [comment]
> > > > I think there is no way to specify a branch for this repo when testing
> > > 
> > > 
> > > Good point. Maybe we need to amend that management command to allow for different branches on staging for testing?
> > 
> > 
> > @wakibi want to add that as part of this update?
> 
> Sure. Let me work on this

@edwinmp PR for choosing branch [here](https://github.com/devinit/ddw-analyst-ui/pull/466). 
@akmiller01 both these have been deployed to staging.
Cheers

**Pull request merged**
